secrets: my_secrets.yml


schedules:
  # Run every task every 1 hour
  - tasks: '*'
    interval:
      hours: 1


web_server:
  bind: 0.0.0.0
  port: 5050
api: yes
webui: yes

##### TEMPLATES
#
templates:
  ##### Global config
  #
  global:
    no_entries_ok: yes
    pathscrub: windows
    free_space:
      path: '/{{secrets.folder.root}}'
      space: 4096
    # Requires log_filter plugin
    log_filter:
      task:
        - marked seen
        - because quality already downloaded
        - because episode has already been downloaded
        - Task does not have any
      move:
        - left because it exceeds safety value
        - does not exists (anymore)
      urlrewriter:
        - URL rewritten to
      enzyme.mkv:
        - Reading
        - Processing
      enzyme.parsers.ebml.core:
        - ignored
        - Maximum level
      subliminal.video:
        - Scanning video
      parser_internal:
        - appears to be an episode pack
      content_size:
        - rejecting
      search_rss:
        - Error
      assume_quality:
        - ""
      utils.requests:
        - Waiting

  ##### Mail config
  #
  email-template:
    email:
      from: '{{ secrets.gmail.user }}'
      to: '{{ secrets.gmail.user }}'
      smtp_host: smtp.gmail.com
      smtp_port: 465
      smtp_username: '{{ secrets.gmail.user }}'
      smtp_password: '{{ secrets.gmail.password }}'
      smtp_tls: yes
      smtp_ssl: yes

  ##### Series config
  #
  series:
    thetvdb_lookup: yes
    trakt_lookup: yes
    include: series.yml
    configure_series:
      from:
        entry_list: trakt-series
      settings:
        identified_by: ep
        timeframe: 15 minutes
        target: hdtv 720p
        quality: webrip+ 720p
        propers: 16 hours
        specials: no
    content_size:
      min: 350
    content_filter:
      require:
        - '*.mkv'
#    archive: [episodes]

  ##### Movies config
  #
  movies-1080p:
    tmdb_lookup: yes
    movie_list: trakt-movies
    quality: 1080p webdl+
    content_size:
      min: 1000
      max: 8000
    archive: [movies]

  movies-720p:
    tmdb_lookup: yes
    movie_list: trakt-movies
    quality: 720p webdl+
    content_size:
      min: 500
      max: 3000
    archive: [movies]

  ##### Pushbullet config
  #
  pushbullet:
    pushbullet:
      apikey: '{{secrets.pushbullet.api}}'
      title: "[Flexget] {{task}}"
      body: "{{title}}"

  ##### Common rejections
  #
  regex:
    regexp:
      reject:
        - (s|d)ub(s|bed|lado|titulado)?\b
        - \bdual\b
        - \b3d\b
        - \b(fr)(ench)?\b
        - \b(ita)(lian)?\b
        - \b(spa)(nish)?\b
        - \b(ger)(man)?\b
        - \bcastellano\b
        - \brus(sian)?\b
        - \bchs\b
    content_filter:
      reject:
        - '*.rar'
        - '*.zip'

  ##### Common torrents config
  #
  torrents:
    torrent_alive:
      min_seeds: 10
      reject_for: 15 minutes
    magnets: no
    # Might need to disable if you are getting errors connecting to https sources
    # Can remove if you upgrade to python 2.7.9+ or install requests[security]
    #verify_ssl_certificates: no
    domain_delay:
      torrentz.eu: 1 seconds
      unblocked.la: 1 seconds

##### Transmission config
#
  transmission:
    transmission:
      host: '{{secrets.transmission.host}}'
      port: 9091
      username: '{{secrets.transmission.user}}'
      password: '{{secrets.transmission.pass}}'
      main_file_only: yes
      include_subs: yes
      skip_files:
        - '*.nfo'
        - '*.sfv'
        - '*.txt'
        - '*[sS]ample*'
        - '*[tT]railer*'

##### Transmission series config
#
  transmission-series:
    transmission:
      # trakt lookup
      #content_filename: "{{trakt_series_name|default(series_name)|pathscrub}} - {{trakt_ep_id|default(series_id)}}{% if trakt_ep_name|default(False) %}: - {{trakt_ep_name|escape|replace('&#39;', '')|pathscrub}}{% endif %}{% if quality|default(False) %}: - [{{quality}}]{% endif %}{% if proper_count %} PROPER{% if proper_count > 1 %}{{proper_count}}{% endif %}{% endif %}"
      #path: "/{{secrets.folder.downseries}}{{trakt_series_name|default(series_name)|pathscrub}}/S{{trakt_season|pad(2)}}/"

      # thetvdb lookup
      content_filename: "{{tvdb_series_name|default(series_name)|pathscrub}} - {{tvdb_ep_id|default(series_id)}}{% if tvdb_ep_name|default(False) %}: - {{tvdb_ep_name|escape|replace('&#39;', '')|pathscrub}}{% endif %}{% if quality|default(False) %}: - [{{quality}}]{% endif %}{% if proper_count %} PROPER{% if proper_count > 1 %}{{proper_count}}{% endif %}{% endif %}"
      path: "/{{secrets.folder.downseries}}{{tvdb_series_name|default(series_name)|pathscrub}}/S{{tvdb_season|pad(2)}}/"

      # builtin lookup
      #content_filename: "{{series_name|default(series_name)|pathscrub}} - {{tvdb_ep_id|default(series_id)}}{% if tvdb_ep_name|default(False) %}: - {{tvdb_ep_name|escape|replace('&#39;', '')|pathscrub}}{% endif %}{% if quality|default(False) %}: - [{{quality}}]{% endif %}{% if proper_count %} PROPER{% if proper_count > 1 %}{{proper_count}}{% endif %}{% endif %}"
      #path: "/{{secrets.folder.downseries}}{{series_name|default(series_name)|pathscrub}}/S{{tvdb_season|pad(2)}}/"

  ##### Transmission movies config
  #
  transmission-movies:
    transmission:
      content_filename: "{{tmdb_name|pathscrub}} ({{tmdb_year}}){% if quality|default(False) %}: - [{{quality}}]{% endif %}{% if proper_count %} PROPER{% if proper_count > 1 %}{{proper_count}}{% endif %}{% endif %}"
      path: "/{{secrets.folder.downmovies}}{{movie_name|pathscrub}}"

##### Disable builtins for some tasks
#
  disable-seen-retry:
    disable:
      - seen
      - seen_info_hash
      - retry_failed

##### Series metainfo mainly for move and update tasks
#
  series-metainfo:
    metainfo_series: yes
    thetvdb_lookup: yes
    trakt_lookup: yes

##### Movies metainfo mainly for move and update tasks
#
  movies-metainfo:
    tmdb_lookup: yes
    parsing:
      movie: guessit


##### TASKS
#
tasks:

  ##### Populates the series database with the files on the library, to avoid duplicate downloads
  #
  populate-series-db:
    priority: 1
    interval: 4 hour
    template:
      - series-metainfo
    seen: local
    filesystem:
      path: '/{{secrets.folder.series}}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    configure_series:
      from:
        filesystem:
          path: '/{{secrets.folder.series}}'
          retrieve: dirs
      settings:
        tracking: no


  ##### Purge the series list to allow full sync with trakt series list
  #
  purge-series-list:
    priority: 2
    template:
      - disable-seen-retry
    entry_list: trakt-series
    accept_all: yes
    list_remove:
      - entry_list: trakt-series


  ##### Fetch, format and output trakt series list to temp file
  #
#  fetch-series:
#    priority: 3
#    disable: builtins
#    trakt_list:
#      account: '{{secrets.trakt.account}}'
#      list: '{{secrets.trakt.series}}'
#      type: shows
#      strip_dates: yes
#    thetvdb_lookup: yes
#    trakt_lookup: yes
#    accept_all: yes
#    plugin_priority:
#      # manipulate must fix the titles before metainfo_series.
#      manipulate: 255
#    manipulate:
#      - title:
#          replace:
#            regexp: '^[^a-z0-9]*11\.22\.63[^a-z0-9]*'
#            format: '11-22-63.'
#    set:
#      #title: "{{trakt_series_name|escape|replace('&#39;', '')}}"
#      title: "{{tvdb_series_name|escape|replace('&#39;', '')}}"
#      #title: "{{series_name|escape|replace('&#39;', '')}}"
#    exec:
#      on_start:
#        phase: rm -f '/{{secrets.list.series}}' && touch '/{{secrets.list.series}}'
#      on_output:
#        for_entries: echo "{{title}}" >> '/{{secrets.list.series}}'


  ##### Fetch, format and output trakt series list to a custom entry list
  #
  fill-series-list:
    priority: 3
    template:
      - disable-seen-retry
      - series-metainfo
    trakt_list:
      account: '{{secrets.trakt.account}}'
      list: '{{secrets.trakt.series}}'
      type: shows
    accept_all: yes
    plugin_priority:
      # manipulate must fix the titles before metainfo_series.
      manipulate: 255
    manipulate:
      - title:
          replace:
            regexp: '^[^a-z0-9]*11\.22\.63[^a-z0-9]*'
            format: '11-22-63.'
    set:
      #title: "{{trakt_series_name|escape|replace('&#39;', '')}}"
      title: "{{tvdb_series_name|escape|replace('&#39;', '')}}"
      #title: "{{series_name|escape|replace('&#39;', '')}}"
    list_add:
      - entry_list: trakt-series


  ##### Download episodes from manually downloaded torrents
  #
  download-series-manual:
    priority: 4
#    manual: yes
    template:
      - disable-seen-retry
      - series-metainfo
      - transmission
      - transmission-series
#      - pushbullet
    filesystem:
      path: '/{{secrets.folder.watchseries}}'
      mask: '*.torrent'
    parsing:
      series: guessit
    accept_all: yes
    exec:
      on_output:
        for_accepted: rm -f "{{location}}"


  ##### Download episodes from RSS feeds
  #
  download-series-rss:
    priority: 5
    template:
      - series
      - regex
      - torrents
      - transmission
      - transmission-series
#      - pushbullet
    archive: [episodes]
    inputs:
      - rss:
          url: http://torrentz.eu/feedA?good&q=tv
          all_entries: yes
      - rss:
          url: https://kickass.unblocked.la/tv/?rss=1
          all_entries: yes
#      - rss:
#          url: https://kat.cr/tv/?rss=1
#          all_entries: yes


  ##### Discover and download older episodes and pilots from recently added series, set with interval to avoid spam
  #
  download-series-discover:
    priority: 6
    interval: 4 hour
    template:
      - series
      - regex
      - torrents
      - transmission
      - transmission-series
#      - pushbullet
    discover:
      release_estimations: ignore
      interval: 15 minutes
      what:
        - emit_series:
            from_start: yes
      from:
        - torrentz: good
        - search_rss: https://kickass.unblocked.la/usearch/{{search_term}}/?rss=1
#        - search_rss: https://kat.cr/usearch/{{ search_term }}/?rss=1


  ##### Remove manually movies downloaded from the movie queue and trakt list
  #
  clean-movie-queue:
    priority: 11
    interval: 2 hour
    template:
      - disable-seen-retry
      - movies-metainfo
    filesystem:
      path: '/{{secrets.folder.movies}}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    list_remove:
      - movie_list: trakt-movies
      - trakt_list:
          account: '{{secrets.trakt.account}}'
          list: '{{secrets.trakt.movies}}'
    parsing:
      movie: guessit


  ##### Fill the movie queue with movies from trakt list
  #
  fill-movie-queue:
    priority: 12
    trakt_list:
      account: '{{secrets.trakt.account}}'
      list: '{{secrets.trakt.movies}}'
      type: movies
      strip_dates: yes
    accept_all: yes
    list_add:
      - movie_list: trakt-movies


  ##### Download movies manually downloaded torrents
  #
  download-movies-manual:
    priority: 15
#    manual: yes
    template:
      - disable-seen-retry
      - movies-metainfo
      - transmission
      - transmission-movies
#      - pushbullet
    filesystem:
      path: '/{{secrets.folder.watchmovies}}'
      mask: '*.torrent'
    parsing:
      movie: guessit
    accept_all: yes
    exec:
      on_output:
        for_accepted: rm -f "{{location}}"
    list_remove:
      - trakt_list:
          account: '{{secrets.trakt.account}}'
          list: '{{secrets.trakt.movies}}'


  ##### Download 1080p movies
  #
  download-movies-1080p:
    priority: 16
    interval: 2 hour
    template:
      - movies-1080p
      - regex
      - torrents
      - transmission
      - transmission-movies
#      - pushbullet
    exists_movie:
      - '/{{secrets.folder.downmovies}}'
      - '/{{secrets.folder.movies}}'
    discover:
      release_estimations: ignore
      interval: 15 minutes
      what:
        - movie_list: trakt-movies
      from:
        - flexget_archive: [movies]
        - torrentz: good
        - search_rss: https://kickass.unblocked.la/usearch/{{search_term}}/?rss=1
#        - search_rss: https://kat.cr/usearch/{{ search_term }}/?rss=1
    list_queue:
      - movie_list: trakt-movies
    list_remove:
      - trakt_list:
          account: '{{secrets.trakt.account}}'
          list: '{{secrets.trakt.movies}}'


  ##### Download 720p movies with 1 day delay from higher quality
  #
  download-movies-720p:
    priority: 17
    interval: 4 hour
    delay: 1 day
    template:
      - movies-720p
      - regex
      - torrents
      - transmission
      - transmission-movies
#      - pushbullet
    exists_movie:
      - '/{{secrets.folder.downmovies}}'
      - '/{{secrets.folder.movies}}'
    discover:
      release_estimations: ignore
      interval: 15 minutes
      what:
        - movie_list: trakt-movies
      from:
        - flexget_archive: [movies]
        - torrentz: good
        - search_rss: https://kickass.unblocked.la/usearch/{{search_term}}/?rss=1
#        - search_rss: https://kat.cr/usearch/{{ search_term }}/?rss=1
    list_queue:
      - movie_list: trakt-movies
    list_remove:
      - trakt_list:
          account: '{{secrets.trakt.account}}'
          list: '{{secrets.trakt.movies}}'


  ##### Move series from downloads folder to respective folders, along with existing subtitles and adding the files to the subtitle queue
  #
  move-series:
    priority: 21
    template:
      - disable-seen-retry
      - series-metainfo
      - pushbullet
#      - email-template
    filesystem:
      path: '/{{secrets.folder.downseries}}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
# might be needed for some series, but causes issues with "name (year)" based series, like scandal
#    parsing:
#      series: guessit

    plugin_priority:
      # manipulate must fix the titles before metainfo_series.
      manipulate: 255
    manipulate:
      - title:
          replace:
            regexp: '^[^a-z0-9]*11\.22\.63[^a-z0-9]*'
            format: '11-22-63.'
    accept_all: yes
    regexp:
      reject:
        - \btrailer\b
        - \bsample\b
    move:
      # trakt lookup
      #to: "/media/Tera/Library/TV/{{trakt_series_name|escape|replace('&#39;', '')|pathscrub}}/S{{trakt_season|pad(2)}}/"
      #filename: "{{trakt_series_name|escape|replace('&#39;', '')|pathscrub}} - {{trakt_ep_id|default(series_id)}}{% if trakt_ep_name|default(False) %}: - {{trakt_ep_name|escape|replace('&#39;', '')|pathscrub}}{% endif %}{% if quality|default(False) %}: - [{{quality}}]{% endif %}{% if proper_count %} PROPER{% if proper_count > 1 %}{{proper_count}}{% endif %}{% endif %}"

      # tvdb lookup
#      to: "/media/Tera/Library/TV/{{tvdb_series_name|escape|replace('&#39;', '')|pathscrub}}/S{{tvdb_season|pad(2)}}/"
      to: "/{{secrets.folder.series}}{{tvdb_series_name|escape|replace('&#39;', '')|pathscrub}}/S{{tvdb_season|pad(2)}}/"
      filename: "{{tvdb_series_name|escape|replace('&#39;', '')|pathscrub}} - {{tvdb_ep_id|default(series_id)}}{% if tvdb_ep_name|default(False) %}: - {{tvdb_ep_name|escape|replace('&#39;', '')|pathscrub}}{% endif %}{% if quality|default(False) %}: - [{{quality}}]{% endif %}{% if proper_count %} PROPER{% if proper_count > 1 %}{{proper_count}}{% endif %}{% endif %}"

      # builtin lookup
      #to: "/media/Tera/Library/TV/{{series_name|escape|replace('&#39;', '')|pathscrub}}/S{{series_season|pad(2)}}/"
      #filename: "{{series_name|escape|replace('&#39;', '')|pathscrub}} - {{tvdb_ep_id|default(series_id)}}{% if tvdb_ep_name|default(False) %}: - {{tvdb_ep_name|escape|replace('&#39;', '')|pathscrub}}{% endif %}{% if quality|default(False) %}: - [{{quality}}]{% endif %}{% if proper_count %} PROPER{% if proper_count > 1 %}{{proper_count}}{% endif %}{% endif %}"

      along:
        - srt
        - sub
        - en.srt
        - en.sub
      clean_source: 100
    subtitle_queue:
      action: add
      path: "{{output}}"
    exec:
      on_exit:
        for_accepted: find '/{{secrets.folder.downseries}}'* -type d -empty -delete



  ##### Move movies from downloads folder to the movies folder, along with possible subtitles and adding the files to the subtitle queue
  #
  move-movies:
    priority: 26
    template:
      - disable-seen-retry
      - movies-metainfo
      - pushbullet
#      - email-template
    filesystem:
      path: '/{{secrets.folder.downmovies}}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    parsing:
      movie: guessit
    accept_all: yes
    regexp:
      reject:
        - \btrailer\b
        - \bsample\b
    move:
#      to: "/media/Tera/Library/Movies/{{tmdb_name|pathscrub}} ({{tmdb_year}})"
      to: "/{{secrets.folder.movies}}{{tmdb_name|pathscrub}} ({{tmdb_year}})"
      filename: "{{tmdb_name|pathscrub}} ({{tmdb_year}}){% if quality|default(False) %}: - [{{quality}}]{% endif %}{% if proper_count %} PROPER{% if proper_count > 1 %}{{proper_count}}{% endif %}{% endif %}"
      along:
        - srt
        - sub
        - en.srt
        - en.sub
      clean_source: 100
    subtitle_queue:
      action: add
      path: "{{output}}"
    exec:
      on_exit:
        for_accepted: find '/{{secrets.folder.downmovies}}'* -type d -empty -delete


  ##### Download subtitles for the previously queued files
  #
# Might have issues until final release of subliminal 2.0, see: http://discuss.flexget.com/t/subliminal-error/2023/
  download-subtitles:
    priority: 31
    template:
      - disable-seen-retry
    subtitle_queue: emit
    accept_all: yes
    subliminal:
      exact_match: no
      languages:
        - ita
        - eng
      providers:
        - opensubtitles
        - addic7ed
        - podnapisi
        - thesubdb
        - tvsubtitles


  ##### Clean finished torrents from transmission
  #
  clean-transmission:
    priority: 33
    interval: 1 day
    disable: details
    clean_transmission:
      username: '{{ secrets.transmission.user }}'
      password: '{{ secrets.transmission.password }}'
      transmission_seed_limits: yes


  ##### Update trakt series list and thetvdb series list from local series folders, excluding the ones that already ended
  #
  update-series-list:
    priority: 41
    interval: 1 day
    template:
      - disable-seen-retry
      - series-metainfo
    seen: local
    plugin_priority:
      if: -251
      manipulate: -252
      list_add: -253
    filesystem:
      path: '/{{secrets.folder.series}}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    manipulate:
      - series_season:
          remove: yes
      - series_episode:
          remove: yes
      - title:
          replace:
            regexp: '^[^a-z0-9]*11\.22\.63[^a-z0-9]*'
            format: '11-22-63.'
    accept_all: yes
    if:
      - tvdb_status == 'Ended': reject
    list_add:
      - trakt_list:
          account: '{{secrets.trakt.account}}'
          list: '{{secrets.trakt.series}}'


  ##### Clean the series that already ended from trakt series list and thetvdb series list
  #
  clean-series-list:
    priority: 43
    interval: 1 day
    delay: 8 day
    template:
      - disable-seen-retry
      - series-metainfo
      - pushbullet
    trakt_list:
      account: '{{secrets.trakt.account}}'
      list: '{{secrets.trakt.series}}'
      type: shows
    if:
      - tvdb_status == 'Ended': accept
    list_remove:
      - trakt_list:
          account: '{{secrets.trakt.account}}'
          list: '{{secrets.trakt.series}}'

  ##### final actions
  #
  final_actions:
    priority: 100
    exec:
#      echo "Execution ended"
      kodi-upd.sh
